sonar.projectKey=Elysium-Labs-EU_themis
sonar.organization=elysium-labs-eu

sonar.sources=.
sonar.exclusions=bin/**,dist/**,scripts/**,**/*_test.go
sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out
