name: OSV Scan

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  osv-scan:
    name: OSV Scanner
    runs-on: codeberg-small
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Run OSV Scanner
        uses: google/osv-scanner-action/osv-scanner-action@v2
        with:
          scan-args: |-
            --lockfile=go.mod
            --recursive
            .
